# Generated by Django 3.2.5 on 2021-08-29 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_newsstory_img_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsstory',
            old_name='img_url',
            new_name='img_upload',
        ),
    ]
